import React, { useState, useEffect } from "react";
import FixturesDisplay from "./FixturesDisplay";
import styles from "./Fixtures.module.css";

const Fixtures = () => {
  const matches = [
    {
      date: "2022-08-05",
      venue: "Selhurst Park",
      competition: { name: "Premier League", id: 1 },
      id: 407893,
      time: "20:00",
      "home-team": {
        score: 0,
        "half-time-score": 0,
        name: "Crystal Palace",
        id: 8,
      },
      referee: "Anthony Taylor",
      "away-team": { score: 2, "half-time-score": 1, name: "Arsenal", id: 1 },
      attendance: 25286,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-08-13",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 407904,
      time: "15:00",
      "home-team": { score: 4, "half-time-score": 2, name: "Arsenal", id: 1 },
      referee: "England Darren",
      "away-team": {
        score: 2,
        "half-time-score": 0,
        name: "Leicester City",
        id: 30,
      },
      attendance: 60033,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-08-20",
      venue: "Vitality Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 407894,
      time: "17:30",
      "home-team": {
        score: 0,
        "half-time-score": 0,
        name: "AFC Bournemouth",
        id: 47,
      },
      referee: "Craig Pawson",
      "away-team": { score: 3, "half-time-score": 2, name: "Arsenal", id: 1 },
      attendance: 10423,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-08-27",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 407864,
      time: "17:30",
      "home-team": { score: 2, "half-time-score": 0, name: "Arsenal", id: 1 },
      referee: "Jarred Gillett",
      "away-team": { score: 1, "half-time-score": 0, name: "Fulham", id: 10 },
      attendance: 60164,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-08-31",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 413623,
      time: "19:30",
      "home-team": { score: 2, "half-time-score": 1, name: "Arsenal", id: 1 },
      referee: "Robert Jones",
      "away-team": {
        score: 1,
        "half-time-score": 0,
        name: "Aston Villa",
        id: 2,
      },
      attendance: 60012,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-09-04",
      venue: "Old Trafford",
      competition: { name: "Premier League", id: 1 },
      id: 413669,
      time: "16:30",
      "home-team": {
        score: 3,
        "half-time-score": 1,
        name: "Manchester United",
        id: 13,
      },
      referee: "Paul Tierney",
      "away-team": { score: 1, "half-time-score": 0, name: "Arsenal", id: 1 },
      attendance: 73431,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-09-08",
      venue: "Kybunpark",
      round: { name: "Group A", id: 13 },
      competition: { name: "UEFA Europa League", id: 25 },
      id: 424274,
      time: "17:45",
      "home-team": {
        score: 1,
        "half-time-score": 1,
        name: "FC Zurich",
        id: 578,
      },
      referee: "Mohammed Al-Hakim",
      "away-team": { score: 2, "half-time-score": 1, name: "Arsenal", id: 1 },
      attendance: 17070,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-09-18",
      venue: "Gtech Community Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 413671,
      time: "12:00",
      "home-team": {
        score: 0,
        "half-time-score": 0,
        name: "Brentford",
        id: 49,
      },
      referee: "David Coote",
      "away-team": { score: 3, "half-time-score": 2, name: "Arsenal", id: 1 },
      attendance: 17122,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-10-01",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 407994,
      time: "12:30",
      "home-team": { score: 3, "half-time-score": 1, name: "Arsenal", id: 1 },
      referee: "Anthony Taylor",
      "away-team": {
        score: 1,
        "half-time-score": 1,
        name: "Tottenham Hotspur",
        id: 19,
      },
      attendance: 60278,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-10-06",
      venue: "Emirates Stadium",
      round: { name: "Group A", id: 13 },
      competition: { name: "UEFA Europa League", id: 25 },
      id: 424306,
      time: "20:00",
      "home-team": { score: 3, name: "Arsenal", id: 1 },
      referee: "Harm Osmers",
      "away-team": { score: 0, name: "FK Bodø/Glimt", id: 2534 },
      attendance: 0,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-10-09",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 422544,
      time: "16:30",
      "home-team": { score: 3, "half-time-score": 2, name: "Arsenal", id: 1 },
      referee: "Michael Oliver",
      "away-team": {
        score: 2,
        "half-time-score": 1,
        name: "Liverpool",
        id: 11,
      },
      attendance: 59968,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-10-13",
      venue: "Aspmyra Stadion",
      round: { name: "Group A", id: 13 },
      competition: { name: "UEFA Europa League", id: 25 },
      id: 424337,
      time: "17:45",
      "home-team": { score: 0, name: "FK Bodø/Glimt", id: 2534 },
      referee: "Irfan Peljto",
      "away-team": { score: 1, name: "Arsenal", id: 1 },
      attendance: 0,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-10-16",
      venue: "Elland Road",
      competition: { name: "Premier League", id: 1 },
      id: 422550,
      time: "14:00",
      "home-team": {
        score: 0,
        "half-time-score": 0,
        name: "Leeds United",
        id: 29,
      },
      referee: "Chris Kavanagh",
      "away-team": { score: 1, "half-time-score": 1, name: "Arsenal", id: 1 },
      attendance: 36700,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-10-20",
      venue: "Emirates Stadium",
      round: { name: "Group A", id: 13 },
      competition: { name: "UEFA Europa League", id: 25 },
      id: 425342,
      time: "18:00",
      "home-team": { score: 1, "half-time-score": 0, name: "Arsenal", id: 1 },
      referee: "Alejandro Hernandez",
      "away-team": {
        score: 0,
        "half-time-score": 0,
        name: "PSV Eindhoven",
        id: 483,
      },
      attendance: 0,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-10-23",
      venue: "St. Mary's Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 422557,
      time: "14:00",
      "home-team": {
        score: 1,
        "half-time-score": 0,
        name: "Southampton",
        id: 18,
      },
      referee: "Robert Jones",
      "away-team": { score: 1, "half-time-score": 1, name: "Arsenal", id: 1 },
      attendance: 31145,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-10-27",
      venue: "Philips Stadion",
      round: { name: "Group A", id: 13 },
      competition: { name: "UEFA Europa League", id: 25 },
      id: 424321,
      time: "17:45",
      "home-team": {
        score: 2,
        "half-time-score": 0,
        name: "PSV Eindhoven",
        id: 483,
      },
      referee: "Marco Di Bello",
      "away-team": { score: 0, "half-time-score": 0, name: "Arsenal", id: 1 },
      attendance: 0,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-10-30",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 422560,
      time: "14:00",
      "home-team": { score: 5, "half-time-score": 1, name: "Arsenal", id: 1 },
      referee: "Simon Hooper",
      "away-team": {
        score: 0,
        "half-time-score": 0,
        name: "Nottingham Forest",
        id: 32,
      },
      attendance: 60263,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-11-03",
      venue: "Emirates Stadium",
      round: { name: "Group A", id: 13 },
      competition: { name: "UEFA Europa League", id: 25 },
      id: 424353,
      time: "20:00",
      "home-team": { score: 1, "half-time-score": 1, name: "Arsenal", id: 1 },
      referee: "Eric Lambrechts",
      "away-team": {
        score: 0,
        "half-time-score": 0,
        name: "FC Zurich",
        id: 578,
      },
      attendance: 48500,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-11-06",
      venue: "Stamford Bridge",
      competition: { name: "Premier League", id: 1 },
      id: 425336,
      time: "12:00",
      "home-team": { score: 0, "half-time-score": 0, name: "Chelsea", id: 7 },
      referee: "Michael Oliver",
      "away-team": { score: 1, "half-time-score": 0, name: "Arsenal", id: 1 },
      attendance: 40142,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-11-09",
      venue: "Emirates Stadium",
      round: { name: "Third Round", id: 29 },
      competition: { name: "Carabao Cup", id: 22 },
      id: 425477,
      time: "19:45",
      "home-team": { score: 1, "half-time-score": 1, name: "Arsenal", id: 1 },
      referee: "J. Gillett",
      "away-team": {
        score: 3,
        "half-time-score": 1,
        name: "Brighton & Hove Albion",
        id: 21,
      },
      attendance: 59233,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-11-12",
      venue: "Molineux Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 408023,
      time: "19:45",
      "home-team": {
        score: 0,
        "half-time-score": 0,
        name: "Wolverhampton Wanderers",
        id: 44,
      },
      referee: "Stuart Attwell",
      "away-team": { score: 2, "half-time-score": 0, name: "Arsenal", id: 1 },
      attendance: 31523,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-12-26",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 408034,
      time: "20:00",
      "home-team": { score: 3, "half-time-score": 0, name: "Arsenal", id: 1 },
      referee: "Michael Oliver",
      "away-team": {
        score: 1,
        "half-time-score": 1,
        name: "West Ham United",
        id: 42,
      },
      attendance: 60125,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2022-12-31",
      venue: "The American Express Community Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 408025,
      time: "17:30",
      "home-team": {
        score: 2,
        "half-time-score": 0,
        name: "Brighton & Hove Albion",
        id: 21,
      },
      referee: "Anthony Taylor",
      "away-team": { score: 4, "half-time-score": 2, name: "Arsenal", id: 1 },
      attendance: 31647,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-01-03",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 426620,
      time: "19:45",
      "home-team": { score: 0, "half-time-score": 0, name: "Arsenal", id: 1 },
      referee: "Andy Madley",
      "away-team": {
        score: 0,
        "half-time-score": 0,
        name: "Newcastle United",
        id: 15,
      },
      attendance: 60319,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-01-09",
      venue: "The Kassam Stadium",
      round: { name: "Third Round", id: 29 },
      competition: { name: "Emirates FA Cup", id: 21 },
      id: 427969,
      time: "20:00",
      "home-team": {
        score: 0,
        "half-time-score": 0,
        name: "Oxford United",
        id: 84,
      },
      referee: "David Coote",
      "away-team": { score: 3, "half-time-score": 0, name: "Arsenal", id: 1 },
      attendance: 11538,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-01-15",
      venue: "Tottenham Hotspur Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 427466,
      time: "16:30",
      "home-team": {
        score: 0,
        "half-time-score": 0,
        name: "Tottenham Hotspur",
        id: 19,
      },
      referee: "Craig Pawson",
      "away-team": { score: 2, "half-time-score": 2, name: "Arsenal", id: 1 },
      attendance: 61870,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-01-22",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 427463,
      time: "16:30",
      "home-team": { score: 3, "half-time-score": 1, name: "Arsenal", id: 1 },
      referee: "Anthony Taylor",
      "away-team": {
        score: 2,
        "half-time-score": 1,
        name: "Manchester United",
        id: 13,
      },
      attendance: 60325,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-01-27",
      venue: "Etihad Stadium",
      round: { name: "Fourth Round", id: 31 },
      competition: { name: "Emirates FA Cup", id: 21 },
      id: 454680,
      time: "20:00",
      "home-team": {
        score: 1,
        "half-time-score": 0,
        name: "Manchester City",
        id: 12,
      },
      referee: "Paul Tierney",
      "away-team": { score: 0, "half-time-score": 0, name: "Arsenal", id: 1 },
      attendance: 51694,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-02-04",
      venue: "Goodison Park",
      competition: { name: "Premier League", id: 1 },
      id: 408078,
      time: "12:30",
      "home-team": { score: 1, "half-time-score": 0, name: "Everton", id: 9 },
      referee: "David Coote",
      "away-team": { score: 0, "half-time-score": 0, name: "Arsenal", id: 1 },
      attendance: 39314,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-02-11",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 408084,
      time: "15:00",
      "home-team": { score: 1, "half-time-score": 0, name: "Arsenal", id: 1 },
      referee: "Peter Bankes",
      "away-team": {
        score: 1,
        "half-time-score": 0,
        name: "Brentford",
        id: 49,
      },
      attendance: 60254,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-02-15",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 427804,
      time: "19:30",
      "home-team": { score: 1, "half-time-score": 1, name: "Arsenal", id: 1 },
      referee: "Anthony Taylor",
      "away-team": {
        score: 3,
        "half-time-score": 1,
        name: "Manchester City",
        id: 12,
      },
      attendance: 60276,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-02-18",
      venue: "Villa Park",
      competition: { name: "Premier League", id: 1 },
      id: 408094,
      time: "12:30",
      "home-team": {
        score: 2,
        "half-time-score": 2,
        name: "Aston Villa",
        id: 2,
      },
      referee: "Simon Hooper",
      "away-team": { score: 4, "half-time-score": 1, name: "Arsenal", id: 1 },
      attendance: 42066,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-02-25",
      venue: "King Power Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 408109,
      time: "15:00",
      "home-team": {
        score: 0,
        "half-time-score": 0,
        name: "Leicester City",
        id: 30,
      },
      referee: "Craig Pawson",
      "away-team": { score: 1, "half-time-score": 0, name: "Arsenal", id: 1 },
      attendance: 32227,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-03-01",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 455636,
      time: "19:45",
      "home-team": { score: 4, "half-time-score": 2, name: "Arsenal", id: 1 },
      referee: "Michael Oliver",
      "away-team": { score: 0, "half-time-score": 0, name: "Everton", id: 9 },
      attendance: 60213,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-03-04",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 408114,
      time: "15:00",
      "home-team": { score: 3, "half-time-score": 0, name: "Arsenal", id: 1 },
      referee: "Chris Kavanagh",
      "away-team": {
        score: 2,
        "half-time-score": 1,
        name: "AFC Bournemouth",
        id: 47,
      },
      attendance: 60222,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-03-09",
      venue: "Estádio José Alvalade",
      round: { name: "Round of 16", id: 51 },
      competition: { name: "UEFA Europa League", id: 25 },
      id: 456007,
      time: "17:45",
      "home-team": {
        score: 2,
        "half-time-score": 1,
        name: "Sporting Lisbon",
        id: 996,
      },
      referee: "Tobias Stieler",
      "away-team": { score: 2, "half-time-score": 1, name: "Arsenal", id: 1 },
      attendance: 36006,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-03-12",
      venue: "Craven Cottage",
      competition: { name: "Premier League", id: 1 },
      id: 455215,
      time: "14:00",
      "home-team": { score: 0, "half-time-score": 0, name: "Fulham", id: 10 },
      referee: "David Coote",
      "away-team": { score: 3, "half-time-score": 3, name: "Arsenal", id: 1 },
      attendance: 24426,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-03-16",
      venue: "Emirates Stadium",
      round: { name: "Round of 16", id: 51 },
      competition: { name: "UEFA Europa League", id: 25 },
      id: 456016,
      time: "20:00",
      "home-team": {
        score: 1,
        "aggregate-score": 3,
        "half-time-score": 1,
        name: "Arsenal",
        id: 1,
        "penalties-score": 3,
      },
      referee: "Antonio Mateu Lahoz",
      "away-team": {
        score: 1,
        "aggregate-score": 3,
        "half-time-score": 0,
        name: "Sporting Lisbon",
        id: 996,
        "penalties-score": 5,
      },
      attendance: 59929,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-03-19",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 455218,
      time: "14:00",
      "home-team": { score: 4, "half-time-score": 2, name: "Arsenal", id: 1 },
      referee: "Stuart Attwell",
      "away-team": {
        score: 1,
        "half-time-score": 0,
        name: "Crystal Palace",
        id: 8,
      },
      attendance: 60247,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-04-01",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 408147,
      time: "15:00",
      "home-team": { score: 4, "half-time-score": 1, name: "Arsenal", id: 1 },
      referee: "England Darren",
      "away-team": {
        score: 1,
        "half-time-score": 0,
        name: "Leeds United",
        id: 29,
      },
      attendance: 60283,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-04-09",
      venue: "Anfield",
      competition: { name: "Premier League", id: 1 },
      id: 455911,
      time: "16:30",
      "home-team": {
        score: 2,
        "half-time-score": 1,
        name: "Liverpool",
        id: 11,
      },
      referee: "Paul Tierney",
      "away-team": { score: 2, "half-time-score": 2, name: "Arsenal", id: 1 },
      attendance: 53267,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-04-16",
      venue: "London Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 455915,
      time: "14:00",
      "home-team": {
        score: 2,
        "half-time-score": 1,
        name: "West Ham United",
        id: 42,
      },
      referee: "David Coote",
      "away-team": { score: 2, "half-time-score": 2, name: "Arsenal", id: 1 },
      attendance: 62475,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-04-21",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 455916,
      time: "20:00",
      "home-team": { score: 3, "half-time-score": 1, name: "Arsenal", id: 1 },
      referee: "Simon Hooper",
      "away-team": {
        score: 3,
        "half-time-score": 2,
        name: "Southampton",
        id: 18,
      },
      attendance: 60175,
      status: { short: "FT", full: "Full Time" },
    },
    {
      date: "2023-04-26",
      venue: "Etihad Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 408146,
      time: "20:00",
      "home-team": { score: 0, name: "Manchester City", id: 12 },
      referee: "M. Oliver",
      "away-team": { score: 0, name: "Arsenal", id: 1 },
      attendance: 0,
      status: { short: "8pm", full: "Kick off 8pm" },
    },
    {
      date: "2023-05-02",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 457133,
      time: "20:00",
      "home-team": { score: 0, name: "Arsenal", id: 1 },
      "away-team": { score: 0, name: "Chelsea", id: 7 },
      attendance: 0,
      status: { short: "8pm", full: "Kick off 8pm" },
    },
    {
      date: "2023-05-07",
      venue: "St. James' Park",
      competition: { name: "Premier League", id: 1 },
      id: 456844,
      time: "16:30",
      "home-team": { score: 0, name: "Newcastle United", id: 15 },
      "away-team": { score: 0, name: "Arsenal", id: 1 },
      attendance: 0,
      status: { short: "4.30pm", full: "Kick off 4.30pm" },
    },
    {
      date: "2023-05-14",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 457056,
      time: "16:30",
      "home-team": { score: 0, name: "Arsenal", id: 1 },
      "away-team": { score: 0, name: "Brighton & Hove Albion", id: 21 },
      attendance: 0,
      status: { short: "4.30pm", full: "Kick off 4.30pm" },
    },
    {
      date: "2023-05-20",
      venue: "The City Ground",
      competition: { name: "Premier League", id: 1 },
      id: 408210,
      time: "17:30",
      "home-team": { score: 0, name: "Nottingham Forest", id: 32 },
      "away-team": { score: 0, name: "Arsenal", id: 1 },
      attendance: 0,
      status: { short: "5.30pm", full: "Kick off 5.30pm" },
    },
    {
      date: "2023-05-28",
      venue: "Emirates Stadium",
      competition: { name: "Premier League", id: 1 },
      id: 408234,
      time: "16:30",
      "home-team": { score: 0, name: "Arsenal", id: 1 },
      "away-team": { score: 0, name: "Wolverhampton Wanderers", id: 44 },
      attendance: 0,
      status: { short: "4.30pm", full: "Kick off 4.30pm" },
    },
  ];

  const [fixtures, setFixtures] = useState(matches);
  const [team, setTeam] = useState(0);

  // const getData = async () => {
  //   const url =
  //     "https://football-web-pages1.p.rapidapi.com/fixtures-results.json?comp=1&round=1&team=1";

  //   const res = await fetch(url, {
  //     method: "GET",
  //     headers: {
  //       "content-type": "application/octet-stream",
  //       "X-RapidAPI-Key": "910e7f07efmsh51a592a0d9a776ep192c8ajsn6af7a77bdfaa",
  //       "X-RapidAPI-Host": "football-web-pages1.p.rapidapi.com",
  //     },
  //   });

  //   const data = await res.json();
  //   console.log(data["fixtures-results"].matches);

  //   setFixtures(data["fixtures-results"].matches);
  // };

  // useEffect(() => {
  //   getData();
  // }, []);

  return (
    <div className="container">
      <div className="row">
        <label>
          Team:
          <select
            className="col-md-2"
            value={team}
            onChange={(e) => setTeam(e.target.value)}
          >
            <option value="0" key="0">
              Pls select team
            </option>
            {/* {fixtures.map((item) => {
              return (
                <option value={item} key={team}>
                  {item.team}
                </option>
              );
            })} */}
          </select>
        </label>
      </div>
      {/* {fixtures.map((item) => {
        return <div key={item.id}>{item.date}</div>;
      })} */}
      {/* <div className="row">
        <div className="col-md-3">{JSON.stringify(fixtures[0].date)}</div>
      </div> */}

      {/* {fixtures.map((item) => {
        if (
          item["home-team"].name.includes("Arsenal") &&
          item.competition.name.includes("Premier League")
        ) {
          return <div key={item.id}>{item.date}</div>;
        }
      })} */}

      <div className="team">
        <h1>Arsenal</h1>
        <button className="home">Home</button>
        <button className="away">Away</button>
      </div>
      <br />
      <FixturesDisplay
        date={fixtures.date}
        venue={fixtures.venue}
        time={fixtures.time}
        // homeTeam={fixtures["home-team"].name}
        // awayTeam={fixtures["away-team"].name}
        fixtures={fixtures}
      />
    </div>
  );
};

export default Fixtures;
